refactor: change the way action filter checks custom attribute in controller
SharpGrip/FluentValidation.AutoValidation pull request #3
Opened 2023-08-30 17:46 UTC by alshuriga

I've changed the way of mvc action filter checking if controller has FluentValidationAutoValidation attribute.
Tested it in WeatherForecast (dotnet webapi template app) and it seems to work fine.

2023-08-30 23:14 UTC, mvdgun requested changes
@alshuriga thanks for your contribution! I am seeing some binary files in your PR, perhaps some artifacts from your IDE? Could you remove those? I've marked those files for you.

2023-08-30 23:14 UTC, mvdgun commented on .vs/FluentValidation.AutoValidation/FileContentIndex/0b76e120-00f5-4fdb-8a89-982690eeb349.vsidx
remove

2023-08-30 23:14 UTC, mvdgun commented on .vs/FluentValidation.AutoValidation/FileContentIndex/read.lock
remove

2023-08-30 23:14 UTC, mvdgun commented on .vs/FluentValidation.AutoValidation/v17/TestStore/0/000.testlog
remove

2023-08-30 23:14 UTC, mvdgun commented on .vs/FluentValidation.AutoValidation/v17/TestStore/0/testlog.manifest
remove

2023-08-30 23:33 UTC, mvdgun commented
Looking back at the code I think the annotations on methods will break since it only retrieves annotations on the type. Did you test putting an annotation on a controller method?

2023-08-31 07:13 UTC, alshuriga commented
> Looking back at the code I think the annotations on methods will break since it only retrieves annotations on the type. Did you test putting an annotation on a controller method?

thank you fot noticing that, it works now for both controller and action annotation.

2023-09-04 17:18 UTC, mvdgun commented
@alshuriga I'm still debating whether this change will have a detrimental impact on performance since it uses reflection. Where possible I would like to avoid using reflection. I'm going to look into the `EndpointMetadata` some more. Maybe .NET offers some public API's that expose the applied attributes.

2023-09-05 08:36 UTC, alshuriga commented
@mvdgun Yes, GetCustomAttribute actually does impact performance if called every request. I found another way to retrieve attributes, it actually seems to work very similar to the original logic, but there's no restrictions in the documentation for using it in application code. Please take a look.

2023-09-05 14:56 UTC, mvdgun requested changes
@alshuriga Looks like a great option! I have added some remarks.

2023-09-05 14:56 UTC, mvdgun commented on FluentValidation.AutoValidation.Mvc/src/Filters/FluentValidationAutoValidationActionFilter.cs
> +
@alshuriga remove empty line

2023-09-05 14:56 UTC, mvdgun commented on FluentValidation.AutoValidation.Mvc/src/Filters/FluentValidationAutoValidationActionFilter.cs
> +
@alshuriga remove empty line

2023-09-05 14:56 UTC, mvdgun commented on FluentValidation.AutoValidation.Mvc/src/Filters/FluentValidationAutoValidationActionFilter.cs
> +                if (autoValidationMvcConfiguration.ValidationStrategy == ValidationStrategy.Annotations && !context.HttpContext.GetEndpoint().Metadata.OfType<FluentValidationAutoValidationAttribute>(
@alshuriga the `HttpContext.GetEndpoint()` method can return null. Can you move the endpoint to a new variable called `endpoint` above the `var actionDescriptor` and check for null in the if at line 36?

2023-09-05 17:15 UTC, mvdgun commented
Closes #4

2023-09-05 17:15 UTC, mvdgun approved these changes

2023-09-05 17:15 UTC, merged

2023-09-05 17:16 UTC, mvdgun commented
Merged, thanks for you contribution @alshuriga!